setwd("C:/Users/bjr30/source/repos/bredlich/cpp-learning")

data <- read.csv("sine_wave.csv")

plot(data$x, data$y, type = "l",
     main = "Sine Wave Generated by C++",
     xlab = "x", ylab = "sin(x)")